# Generated by Django 4.2.5 on 2023-10-02 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_lesson_is_completed_lesson_watched_time_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='watched_time_seconds',
        ),
        migrations.AddField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(related_name='lessons', to='polls.product'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_seconds',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='LessonWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_time_seconds', models.IntegerField()),
                ('is_completed', models.BooleanField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
