# Generated by Django 4.2.5 on 2023-10-02 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_remove_product_owners_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='user',
        ),
        migrations.AddField(
            model_name='access',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
