# Generated by Django 4.2.5 on 2023-10-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_access_user_access_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonwatched',
            name='last_watched_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
