# Generated by Django 4.2.5 on 2023-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_lessonwatched_last_watched_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonwatched',
            name='watched_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
