# Generated by Django 4.2.5 on 2023-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_lesson_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonwatched',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
